name: My Site
favicon: null
layout_spectrum: 0.3049830268137157
typography_spectrum: 0.4760924386791885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0a'
    - '#fffffe'
    - '#e47935'
    - '#71b844'
    - '#ff0000'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
